// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Model_Update_BasedOn_Exersice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Model_Update_BasedOn_Exersice));
        
        string IMigrationMetadata.Id
        {
            get { return "201810111232587_Model_Update_BasedOn_Exersice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
